import pandas as pd
df=pd.read_excel('50 Hands/Mobility Data/GoogleMobility.xlsx',sheet_name='Sheet1')
df2=pd.read_excel('50 Hands/Mobility Data/HistoricalData2.xlsx',sheet_name='USA')
df3=pd.read_excel('50 Hands/Mobility Data/HistoricalData2.xlsx',sheet_name='Canada')
df4=pd.read_excel('50 Hands/Mobility Data/CountyData.xlsx',sheet_name='Sheet1')
print('Loaded!!')
df2=df2.append(df3,ignore_index=True)
df2=df2.append(df4,ignore_index=True)
print('Loaded 2!!')
df=pd.merge(df,df2,how='left',left_on=['country_region','sub_region_1','sub_region_2','date'],right_on=['country_region','sub_region_1','sub_region_2','date'])
print('Loaded 3!!')
df=df.fillna(0)
writer=pd.ExcelWriter('50 Hands/Mobility Data/GoogleMobilityData.xlsx',engine='xlsxwriter')
df.to_excel(writer,sheet_name='Sheet1',index=False)
writer.save()
